"""Deterministic drop rules.

R7: filtering starts conservative — exact-hash duplicates and short structural
boilerplate only — and every drop is returned with the text and the rule that
fired so thresholds can be reviewed after a real dataset without re-ingesting.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

from kg_contracts import Chunk, PrefilterDecision, PrefilterOutcome

# Anchored, structural patterns only. Anything fuzzier risks dropping real content.
_BOILERPLATE_RULES: list[tuple[str, re.Pattern[str]]] = [
    ("confidentiality_footer", re.compile(r"^this (e-?mail|message) .{0,120}confidential", re.I)),
    ("unsubscribe_footer", re.compile(r"^(to )?unsubscribe\b", re.I)),
    ("auto_generated_header", re.compile(r"^(auto|automatically) generated by\b", re.I)),
    ("page_marker", re.compile(r"^page\s+\d+(\s+of\s+\d+)?$", re.I)),
    ("copyright_notice", re.compile(r"^(©|\(c\)|copyright)\s*\d{4}", re.I)),
    ("empty_diff", re.compile(r"^(no changes|empty diff|0 files changed)\b", re.I)),
    ("table_of_contents", re.compile(r"^table of contents$", re.I)),
    ("separator_only", re.compile(r"^[\s\-=_*#|.]+$")),
]


@dataclass
class PrefilterResult:
    kept: list[Chunk] = field(default_factory=list)
    decisions: list[PrefilterDecision] = field(default_factory=list)

    @property
    def total(self) -> int:
        return len(self.decisions)

    @property
    def dropped(self) -> int:
        return sum(1 for d in self.decisions if d.outcome is not PrefilterOutcome.KEPT)

    @property
    def drop_rate(self) -> float:
        return self.dropped / self.total if self.total else 0.0


def _boilerplate_rule(text: str) -> str | None:
    probe = text.strip()
    for name, pattern in _BOILERPLATE_RULES:
        if pattern.search(probe):
            return name
    return None


def prefilter_chunks(
    chunks: list[Chunk],
    *,
    seen_hashes: set[str],
) -> PrefilterResult:
    """Drop exact duplicates and structural boilerplate, paragraph by paragraph.

    `seen_hashes` is mutated as chunks are accepted, so callers can seed it with
    hashes already present in the store to suppress re-ingested content.

    Length-based dropping deliberately happens later, on assembled episodes
    (`prune_short_episodes`), so that a short heading merges with its body
    instead of being discarded on its own.
    """
    result = PrefilterResult()

    for chunk in chunks:
        if chunk.content_hash in seen_hashes:
            result.decisions.append(
                PrefilterDecision(
                    chunk_id=chunk.chunk_id,
                    outcome=PrefilterOutcome.DUPLICATE,
                    rule="exact_hash",
                    dropped_text=chunk.text,
                )
            )
            continue

        rule = _boilerplate_rule(chunk.text)
        if rule is not None:
            result.decisions.append(
                PrefilterDecision(
                    chunk_id=chunk.chunk_id,
                    outcome=PrefilterOutcome.BOILERPLATE,
                    rule=rule,
                    dropped_text=chunk.text,
                )
            )
            continue

        seen_hashes.add(chunk.content_hash)
        result.kept.append(chunk)
        result.decisions.append(
            PrefilterDecision(chunk_id=chunk.chunk_id, outcome=PrefilterOutcome.KEPT)
        )

    return result
