#!/usr/bin/env python3
"""
Synapse v2 Credential Setup Script

Generates a secure .env file with strong secrets and guides you through
configuring external service credentials (GitHub, Gmail, LLM providers).

Usage:
    cd backend
    python scripts/setup_credentials.py
    # Then edit the generated .env with your service credentials
"""

import os
import secrets
import sys
from pathlib import Path

BACKEND_ROOT = Path(__file__).resolve().parent.parent
ENV_PATH = BACKEND_ROOT / ".env"
ENV_EXAMPLE = BACKEND_ROOT / ".env.example"


def gen_jwt_secret() -> str:
    return secrets.token_urlsafe(48)


def gen_api_key() -> str:
    return f"sk-{secrets.token_urlsafe(32)}"


def gen_password(length: int = 16) -> str:
    alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*"
    return "".join(secrets.choice(alphabet) for _ in range(length))


def read_env_example() -> dict:
    """Parse .env.example for structure and comments."""
    if not ENV_EXAMPLE.exists():
        return {}
    config = {}
    current_section = "Core"
    with ENV_EXAMPLE.open() as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                if line.startswith("#"):
                    current_section = line[1:].strip()
                continue
            if "=" in line:
                key, val = line.split("=", 1)
                config[key.strip()] = {"value": val.strip(), "section": current_section}
    return config


def write_env(config: dict) -> None:
    """Write .env file with sections and comments."""
    sections = {}
    for key, info in config.items():
        sections.setdefault(info["section"], []).append((key, info["value"]))

    lines = [
        "# Synapse v2 Configuration",
        "# Generated by setup_credentials.py",
        "# Edit the values below with your actual credentials",
        "",
    ]

    for section, items in sections.items():
        lines.append(f"# === {section} ===")
        for key, val in items:
            lines.append(f"{key}={val}")
        lines.append("")

    ENV_PATH.write_text("\n".join(lines))
    print(f"✅ Written to {ENV_PATH}")


def main():
    print("🔐 Synapse v2 Credential Setup")
    print("=" * 50)

    if ENV_PATH.exists():
        resp = input(f"⚠️  {ENV_PATH} already exists. Overwrite? [y/N]: ").strip().lower()
        if resp != "y":
            print("Aborted.")
            return

    # Base configuration with generated secrets
    config = {
        # Core
        "SYNAPSE_HOST": {"value": "127.0.0.1", "section": "Core"},
        "SYNAPSE_PORT": {"value": "8001", "section": "Core"},
        "SYNAPSE_AUTH_TOKEN": {"value": "", "section": "Core"},
        "SYNAPSE_DATA_DIR": {"value": "./var", "section": "Core"},
        "SYNAPSE_MAX_UPLOAD_BYTES": {"value": "52428800", "section": "Core"},

        # Graph
        "SYNAPSE_GRAPH_BACKEND": {"value": "neo4j", "section": "Graph Backend"},
        "SYNAPSE_GRAPH_DATABASE": {"value": "synapse", "section": "Graph Backend"},
        "SYNAPSE_FALKORDB_HOST": {"value": "localhost", "section": "Graph Backend"},
        "SYNAPSE_FALKORDB_PORT": {"value": "6379", "section": "Graph Backend"},
        "SYNAPSE_NEO4J_URI": {"value": "bolt://localhost:7687", "section": "Graph Backend"},
        "SYNAPSE_NEO4J_USER": {"value": "neo4j", "section": "Graph Backend"},
        "SYNAPSE_NEO4J_PASSWORD": {"value": "password", "section": "Graph Backend"},

        # LLM Provider (choose ONE primary)
        "SYNAPSE_LLM_PROVIDER": {"value": "nvidia", "section": "LLM Provider"},
        "SYNAPSE_OPENAI_API_KEY": {"value": "", "section": "LLM Provider"},
        "SYNAPSE_OPENAI_MODEL": {"value": "deepseek-ai/deepseek-v4-flash-0731", "section": "LLM Provider"},
        "SYNAPSE_OLLAMA_BASE_URL": {"value": "http://localhost:11434/v1", "section": "LLM Provider"},
        "SYNAPSE_OLLAMA_MODEL": {"value": "deepseek-ai/deepseek-v4-flash-0731", "section": "LLM Provider"},
        "SYNAPSE_NVIDIA_API_KEY": {"value": "", "section": "LLM Provider"},
        "SYNAPSE_NVIDIA_BASE_URL": {"value": "https://integrate.api.nvidia.com/v1", "section": "LLM Provider"},
        "SYNAPSE_NVIDIA_MODEL": {"value": "nvidia/nemotron-3-ultra-550b-a55b", "section": "LLM Provider"},
        "SYNAPSE_NVIDIA_EMBEDDING_MODEL": {"value": "nvidia/nemotron-3-embed-1b", "section": "LLM Provider"},
        "SYNAPSE_NVIDIA_EMBEDDING_DIM": {"value": "2048", "section": "LLM Provider"},
        "SYNAPSE_GROQ_API_KEY": {"value": "", "section": "LLM Provider"},
        "SYNAPSE_GROQ_MODEL": {"value": "openai/gpt-oss-120b", "section": "LLM Provider"},
        "SYNAPSE_HF_TOKEN": {"value": "", "section": "LLM Provider"},
        "SYNAPSE_EMBEDDING_DIM": {"value": "1024", "section": "LLM Provider"},

        # GitHub
        "SYNAPSE_GITHUB_APP_ID": {"value": "", "section": "GitHub Connector"},
        "SYNAPSE_GITHUB_APP_PRIVATE_KEY": {"value": "", "section": "GitHub Connector"},
        "SYNAPSE_GITHUB_WEBHOOK_SECRET": {"value": gen_jwt_secret(), "section": "GitHub Connector"},
        "SYNAPSE_GITHUB_EXTERNAL_AGENT_WEBHOOK_URL": {"value": "", "section": "GitHub Connector"},
        "SYNAPSE_GITHUB_DEFAULT_POLL_INTERVAL_HOURS": {"value": "6", "section": "GitHub Connector"},

        # Mail/Gmail
        "SYNAPSE_MAIL_GOOGLE_CLIENT_ID": {"value": "", "section": "Mail/Gmail Connector"},
        "SYNAPSE_MAIL_GOOGLE_CLIENT_SECRET": {"value": "", "section": "Mail/Gmail Connector"},
        "SYNAPSE_MAIL_GOOGLE_REDIRECT_URI": {"value": "http://localhost:5173/mail/oauth/callback", "section": "Mail/Gmail Connector"},
        "SYNAPSE_MAIL_DEFAULT_POLL_INTERVAL_MINUTES": {"value": "15", "section": "Mail/Gmail Connector"},

        # RBAC & Auth
        "SYNAPSE_JWT_SECRET": {"value": gen_jwt_secret(), "section": "RBAC & Authentication"},
        "SYNAPSE_ACCESS_TOKEN_TTL_MINUTES": {"value": "5256000", "section": "RBAC & Authentication"},
        "SYNAPSE_REFRESH_TOKEN_TTL_DAYS": {"value": "3650", "section": "RBAC & Authentication"},
        "SYNAPSE_RBAC_TRANSITION_MODE": {"value": "false", "section": "RBAC & Authentication"},
        "SYNAPSE_BOOTSTRAP_ADMIN_EMAIL": {"value": "", "section": "RBAC & Authentication"},
        "SYNAPSE_BOOTSTRAP_ADMIN_PASSWORD": {"value": gen_password(), "section": "RBAC & Authentication"},
        "SYNAPSE_BOOTSTRAP_ADMIN_DISPLAY_NAME": {"value": "Bootstrap Administrator", "section": "RBAC & Authentication"},
        "SYNAPSE_BOOTSTRAP_ADMIN_API_KEY": {"value": gen_api_key(), "section": "RBAC & Authentication"},

        # Observability
        "SYNAPSE_STRICT_PROMPTS": {"value": "false", "section": "Observability & Pipeline"},
        "SYNAPSE_DYNAMIC_EXTRACTION": {"value": "false", "section": "Observability & Pipeline"},
        "SYNAPSE_PREFILTER_MIN_CHARS": {"value": "40", "section": "Observability & Pipeline"},
        "SYNAPSE_PREFILTER_BATCH_TARGET_CHARS": {"value": "1200", "section": "Observability & Pipeline"},
        "SYNAPSE_RECONCILE_STUCK_AFTER_SECONDS": {"value": "120", "section": "Observability & Pipeline"},
    }

    write_env(config)

    print("\n📋 Next Steps:")
    print("1. Edit .env and fill in YOUR credentials:")
    print("   - LLM Provider: At least one of OPENAI/NVIDIA/GROQ/OLLAMA API keys")
    print("   - GitHub: App ID + Private Key (from GitHub Developer Settings)")
    print("   - Gmail: Google OAuth Client ID + Secret (from Google Cloud Console)")
    print("   - Bootstrap Admin: Email + Password for first admin user")
    print()
    print("2. For NVIDIA NIM (recommended):")
    print("   - Get API key from https://build.nvidia.com")
    print("   - Run: python scripts/check_nvidia.py  # validates credentials")
    print()
    print("3. Start the backend:")
    print("   ./run.sh")
    print()
    print("4. Start the console (in another terminal):")
    print("   cd ../console && npm install && npm run dev")
    print()
    print("5. Access the console at http://localhost:5173")
    print("   Login with bootstrap admin credentials from .env")


if __name__ == "__main__":
    main()